# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
matrix:
    include:
        - os: windows
          language: c
          env: TOXENV=py3
          before_install:
              - choco install python3
              - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - os: osx
          language: generic
          env: TOXENV=py3
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
          dist: xenial
        - os: linux
          python: 3.8-dev
          env: TOXENV=py38
          dist: xenial


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install iputils-ping; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m pip install --user --upgrade pip; fi
  - pip install -U tox
  - pip install tox codecov coveralls
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests, e.g. python setup.py test
script:
  - py.test --cov=ippy tests/
  - tox -e ${TOXENV}

# send coverage
after_success:
  - codecov
  - coveralls
