name: Testing IPpy
on: [push]
jobs:
  build:
    strategy:
      max-parallel: 12
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [27, 35, 36, 37]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: shivammathur/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}    
    - name: Install iputils-ping on Linux
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt-get install iputils-ping
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox pytest-cov        
    - name: Test with tox
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: tox -e py${{ matrix.python-version }}
